### ISSUE TITLE
Unable to find dependencies for libconsole-bridge-dev

### ISSUE THREAD

**Issue by kkspeed** [acowley/roshask#31]
Hi,
I'm trying to use tf with my current project. I added <depends package="tf"/> to the manifest.xml, then I run roshask dep. I receive the following message:

    Looking for ["libconsole-bridge-dev"], dependencies of /home/bruce/catkin_ws/src/lab1
    roshask: Couldn't find path to package (2) libconsole-bridge-dev

It seems that roshask cannot find the package "libconsole-bridge-dev", but this package clearly is installed.

I wonder if I'm doing something wrong or is there any workaround to this?

**Comment by rgleichman** [comment]
It seems that "[libconsole-bridge-dev](https://launchpad.net/ubuntu/trusty/+package/libconsole-bridge-dev)" is not a [ROS Package](http://wiki.ros.org/Packages). Thus it would not be on the `ROS_PACKAGE_PATH`, so roshask would not be able to find it. Try adding "libconsole-bridge-dev" to the list of `ignoredPackages` in [roshask/src/Ros/Internal/DepFinder.hs](https://github.com/acowley/roshask/blob/master/src/Ros/Internal/DepFinder.hs#L65):

```Haskell
ignoredPackages = ["genmsg_cpp", "rospack", "rosconsole", "rosbagmigration", 
                   "roscpp", "rospy", "roslisp", "roslib", "boost", "libconsole-bridge-dev"]
```

**Comment by acowley** [comment]
Hrmph, is it worth trying to find a good way of differentiating these kinds of dependencies? This mechanism works, but doesn't scale very well. On the other hand, it doesn't seem to cause too much trouble, so maybe a hand-maintained list like this is most expedient. We could add some kind of whitelist that could be pulled out of a file (eg, `roshask.ignore`) so folks don't have to edit the code.
