### ISSUE TITLE
please document on ROS wiki

### ISSUE THREAD

**Issue by vrabaud** [acowley/roshask#32]
That looks cool, any way it can end on http://wiki.ros.org/Client%20Libraries ? Thx

**Comment by rgleichman** [comment]
I added roshask to the list of Experimental Client Libraries. Are you also asking for more documentation of roshask on on the ROS wiki?

**Comment by vrabaud** [comment]
I am satisfied with that for now: people need to know it exists so that you can join efforts. Now, if you want to add more docs to the wiki, your call. I don't know how detailed your package doc is. Thx !
