### ISSUE TITLE
haxr 3000.11 :: connection refused

### ISSUE THREAD

**Issue by akru** [acowley/roshask#35]
New haxr version `3000.11` provide a critical bug on node start stage:
```haskell
 Prelude B N A T L> runNode "n" $ advertise "a" (T.repeatM (return (Byte 1)))
*** Exception: connect: does not exist (Connection refused)
```

WireShark says that app access to **443** port, but master port is **11311**.
![wire-haxr](https://cloud.githubusercontent.com/assets/786394/8431113/d736b59c-1f3f-11e5-957a-844d76bf9add.png)

This problem exist only on `3000.11` version of haxr, around this https://github.com/byorgey/haxr/commit/acd31f70f7da0fd9a57cf1fce04bc06eaa51b0e6 seems to me.

**Comment by akru** [comment]
## Temporary solution
`haxr == 3000.10.*` in cabal file.

## About `haxr`
Currently author have migration to `http-streams`. This package doesn't support plain-text HTTP requests(no gzip encoding) by design: http://hackage.haskell.org/package/http-streams-0.3.1.0/docs/src/Network-Http-RequestBuilder.html#http, BUT Python *xmlrpc* based master process doesn't support gzip encoded requests and gives **500** error.

**Comment by acowley** [comment]
Ok, we should get that quick fix in quickly. I've given you push access to the repository, too, btw. The only guideline is that we try to make changes via pull requests so people can comment. Fixing breakage like this can go straight to master. I rebase a lot to avoid incidental merges in the commit history, but that's a best effort thing.

Back to this issue, did you come across evidence that `http-streams` deliberately does not support plain-text? If it's just something they don't support *yet*, we can pull in other `haxr` and `http-streams` developers to the conversation, and/or add support for that ourselves.

**Comment by akru** [comment]
Apparently haxr `3000.11` has a several problems:

1. bugs with port/path capturing from URI;
2. hardcoded https only request;
3. chunked encoding of request data by default.

Items 1 and 2 fixed in https://github.com/akru/haxr/commit/c95025249ee339c4c06c8e74c194f334fcc22682, pull request to author repository created.

Item 3 currently isn't solve.

**Comment by acowley** [comment]
Is the issue of chunked encoding just a matter of calling `setContentLength` somewhere [here](https://github.com/byorgey/haxr/blob/master/Network/XmlRpc/Client.hs#L196)?

**Comment by akru** [comment]
Really, ```content-length``` header is a perfect solution! Patched **haxr** already works with rosmaster.
Waiting for the PR is accepted.

**Comment by akru** [comment]
PR accepted, ```haxr-3000.11.1``` works good.

**Comment by acowley** [comment]
Great that this is resolved. Thanks for taking care of it!
