### ISSUE TITLE
generating Coq as well for ROS message types

### ISSUE THREAD

**Issue by aa755msr** [acowley/roshask#37]
I apologize if this is not the right place to ask this question.

I plan to use roshask to run Coq programs written in the ROSCoq framework:
https://github.com/aa755/ROSCoq

As I start, I want to ROS generate message types for Coq.
I am hoping that with minimal changes, I can get roshask to emit Coq datatype definitions as well along with Haskell definitions for ROS message types. Can someone please point me to some relevant places in the roshask codebase?

Thanks in advance.

**Comment by rgleichman** [comment]
Message generation is done by the roshask executable (whose code is in [roshask/src/executable](https://github.com/acowley/roshask/tree/master/src/executable)). The functions that actually produce the Haskell code for the messages are `generateSrvTypes` (for ROS Services) and `generateMsgType` (for normal ROS messages) which are in [roshask/src/executable/Gen.hs](https://github.com/acowley/roshask/blob/master/src/executable/Gen.hs). `generateSrvTypes` and `generateMsgType` are called by `parseGenWriteService` and `parseGenWriteMsg` in [roshask/src/executable/PkgBuilder.hs](https://github.com/acowley/roshask/blob/master/src/executable/PkgBuilder.hs).

**Comment by aa755msr** [comment]
Thanks @rgleichman. The information you provided was very useful in generating Coq types.
