### ISSUE TITLE
Updating manifest.xml

### ISSUE THREAD

**Issue by theNerd247** [acowley/roshask#39]
First, I'm excited to have found this framework. Ros and Haskell both fit well together conceptually. 
I'm rather new to ROS however I've noticed that rosbuild has been replaced with catkin and in turn most packages use the package.xml format. Can this library use the updated package.xml format?

**Comment by acowley** [comment]
Sorry for the delay on responding to this; your interest is greatly appreciated!

Can you help remind me what is missing at the moment? We have some [support for catkin](https://github.com/acowley/roshask/blob/master/src/Ros/Internal/DepFinder.hs) in tracking down dependencies.

**Comment by theNerd247** [comment]
Ah! I didn't not realize there was already support for catkin. I apologize for the unnecessary issue. On this note I'll mark it as closed - however would it be a bad idea to update the package  generator using the `roshask` command to use the newer catkin package.xml files rather than manifest.xml? I'm referring to  [this][1].

[1]: https://github.com/acowley/roshask/blob/master/src/executable/PkgBuilder.hs
